taskManager/urls.py
#     _  _                        __   __
#  __| |(_)__ _ _ _  __ _ ___   _ \ \ / /
# / _` || / _` | ' \/ _` / _ \_| ' \ V /
# \__,_|/ \__,_|_||_\__, \___(_)_||_\_/
#     |__/          |___/
#
# INSECURE APPLICATION WARNING
#
# django.nV is a PURPOSELY INSECURE web-application
# meant to demonstrate Django security problems
# UNDER NO CIRCUMSTANCES should you take any code
# from django.nV for use in another web application!
#

from django.urls import re_path

from taskManager.views import (
    accounts,
    files,
    projects,
    tasks,
    notes,
    dashboard,
    index
)

from taskManager.views.apis import (
    ogtag
)


app_name = 'taskManager'

urlpatterns = [
    re_path(r'^$', index.index, name='index'),

    # Common
    re_path(r'^dashboard/$', dashboard.dashboard, name='dashboard'),
    re_path(r'^search/$', dashboard.search, name='search'),


    # File
    re_path(r'^files/(?P<file_id>\d+)/$', files.download, name='download'),
    re_path(r'^projects/(?P<project_id>\d+)/files/$',
            files.upload, name='upload'),
    re_path(r'^downloadprofilepic/(?P<user_id>\d+)/$',
            files.download_profile_pic, name='download_profile_pic'),

    # Authentication & Authorization
    re_path(r'^register/$', accounts.register, name='register'),
    re_path(r'^login/$', accounts.login, name='login'),
    re_path(r'^logout/$', accounts.logout_view, name='logout'),
    re_path(r'^profile/$', accounts.profile, name='profile'),
    re_path(r'^change_password/$', accounts.change_password,
            name='change_password'),
    re_path(r'^forgot_password/$', accounts.forgot_password,
            name='forgot_password'),
    re_path(r'^reset_password/$', accounts.reset_password,
            name='reset_password'),
    re_path(r'^profile/(?P<user_id>\d+)$',
            accounts.profile_by_id, name='profile_by_id'),
    re_path(r'^profile_view/(?P<user_id>\d+)$',
            accounts.profile_view, name='profile_view'),

    # Projects
    re_path(r'^projects/create$', projects.project_create,
            name='project_create'),
    re_path(r'^projects/(?P<project_id>\d+)/delete/$',
            projects.project_delete, name='project_delete'),
    re_path(r'^projects/(?P<project_id>\d+)/edit/$',
            projects.project_edit, name='project_edit'),
    re_path(r'^projects/(?P<project_id>\d+)/$',
            projects.project_details, name='project_details'),
    re_path(r'^projects/$', projects.project_list, name='project_list'),

    # Tasks
    re_path(r'^projects/(?P<project_id>\d+)/create/$',
            tasks.task_create, name='task_create'),
    re_path(r'^projects/(?P<project_id>\d+)/tasks/(?P<task_id>\d+)/$',
            tasks.task_details, name='task_details'),
    re_path(r'^projects/(?P<project_id>\d+)/tasks(?P<task_id>\d+)/edit$',
            tasks.task_edit, name='task_edit'),
    re_path(r'^projects/(?P<project_id>\d+)/tasks/(?P<task_id>\d+)/delete$',
            tasks.task_delete, name='task_delete'),
    re_path(r'^projects/(?P<project_id>\d+)/tasks/(?P<task_id>\d+)/complete$',
            tasks.task_complete, name='task_complete'),
    re_path(r'^tasks$', tasks.task_list, name='task_list'),
    re_path(r'^projects/(?P<project_id>\d+)/manage_tasks/$',
            tasks.manage_tasks, name='manage_tasks'),


    # Notes
    re_path(r'^projects/(?P<project_id>\d+)/notes/(?P<task_id>\d+)/notes/create/$',
            notes.note_create, name='note_create'),
    re_path(r'^projects/(?P<project_id>\d+)/notes/(?P<task_id>\d+)/notes/(?P<note_id>\d+)/edit$',
            notes.note_edit, name='note_edit'),
    re_path(r'^projects/(?P<project_id>\d+)/notes/(?P<task_id>\d+)/notes/(?P<note_id>\d+)/delete$',
            notes.note_delete, name='note_delete'),

    # Settings - DEBUG
    re_path(r'^settings/$', index.settings, name='settings'),

    # ogtag api
    re_path(r'^ogtag/$', ogtag.retrive, name='ogtag'),

    # secret page
    re_path(r'^superadmin/$', index.superadmin, name='superadmin'),

    # Admin
    # re_path(r'^admin/', admin.site.urls),
]

taskManager/models.py
#     _  _                        __   __
#  __| |(_)__ _ _ _  __ _ ___   _ \ \ / /
# / _` || / _` | ' \/ _` / _ \_| ' \ V /
# \__,_|/ \__,_|_||_\__, \___(_)_||_\_/
#     |__/          |___/
#
# INSECURE APPLICATION WARNING
#
# django.nV is a PURPOSELY INSECURE web-application
# meant to demonstrate Django security problems
# UNDER NO CIRCUMSTANCES should you take any code
# from django.nV for use in another web application!
#

import datetime

from django.contrib.auth.models import User

from django.utils import timezone
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.CharField(max_length=3000, default="")
    reset_token = models.CharField(max_length=7, default="")
    reset_token_expiration = models.DateTimeField(default=timezone.now)


class Project(models.Model):
    title = models.CharField(max_length=50, default='Default')
    text = models.CharField(max_length=500)
    start_date = models.DateTimeField('date started')
    due_date = models.DateTimeField(
        'date due',
        default=(
            timezone.now() +
            datetime.timedelta(
                weeks=1)))
    users_assigned = models.ManyToManyField(User)
    priority = models.IntegerField(default=1)

    def __str__(self):
        return self.title

    def was_created_recently(self):
        return self.start_date >= timezone.now() - datetime.timedelta(days=1)

    def is_overdue(self):
        return self.due_date <= timezone.now()

    def percent_complete(self):
        counter = 0
        for task in self.task_set.all():
            counter = counter + (1 if task.completed else 0)
        try:
            return round(float(counter) / self.task_set.count() * 100)
        except ZeroDivisionError:
            return 0


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.Case, default=1)
    text = models.CharField(max_length=200)
    title = models.CharField(max_length=200, default="N/A")
    start_date = models.DateTimeField('date created')
    due_date = models.DateTimeField(
        'date due',
        default=(
            timezone.now() +
            datetime.timedelta(
                weeks=1)))
    completed = models.BooleanField(null=True)
    users_assigned = models.ManyToManyField(User)

    def __str__(self):
        return self.text

    def was_created_recently(self):
        return self.start_date >= timezone.now() - datetime.timedelta(days=1)

    def is_overdue(self):
        return self.due_date <= timezone.now()

    def percent_complete(self):
        return 100 if self.completed else 0


class Notes(models.Model):
    task = models.ForeignKey(Task, on_delete=models.Case, default=1)
    title = models.CharField(max_length=200, default="N/A")
    text = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    user = models.CharField(max_length=200, default='ancestor')

    def __str__(self):
        return self.text


class File(models.Model):
    project = models.ForeignKey(Project, on_delete=models.Case)
    name = models.CharField(max_length=300, default="")
    path = models.CharField(max_length=3000, default="")

    def __str__(self):
        return self.name

taskManager/views/accounts.py
import datetime
import os
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.template import RequestContext
from django.db import connection
from django.template import loader

from django.views.decorators.csrf import csrf_exempt

from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User
from django.contrib.auth import logout

from taskManager.models import Project, UserProfile
from taskManager.utils import store_uploaded_file
from taskManager.forms import UserForm, ProfileForm


def login(request):
    template = loader.get_template('accounts/login.html')

    if request.method == 'POST':
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)

        if User.objects.filter(username=username).exists():
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    auth_login(request, user)
                    # Redirect to a success page.
                    return redirect('/dashboard/')
                else:
                    # Return a 'disabled account' error message
                    return redirect('/dashboard/', {'disabled_user': True})
            else:
                # Return an 'invalid login' error message.
                context = {'failed_login': False}
                return HttpResponse(template.render(context, request))
        else:
            context = {'invalid_username': False}
            return HttpResponse(template.render(context, request))
    else:
        return HttpResponse(template.render({}, request))


def register(request):

    context = RequestContext(request)
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            user.set_password(user.password)

            # add user to lowest permission group

            # grp = Group.objects.get(name='team_member')
            # user.groups.add(grp)

            user.userProfile = UserProfile.objects.create(user=user)
            user.userProfile.save()
            user.save()

            # Update our variable to tell the template registration was
            # successful.
            registered = True

        else:
            print(user_form.errors)

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()

    # Render the template depending on the context.

    template = loader.get_template('accounts/register.html')
    context = {'user_form': user_form, 'registered': registered}
    return HttpResponse(template.render(context, request))


def profile(request):
    return render(request, 'accounts/profile.html', {'user': request.user})

def profile_view(request, user_id):
    try:
        user = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        return redirect("/dashboard")

    if request.user.groups.filter(name='admin_g').exists():
        role = "Admin"
    elif request.user.groups.filter(name='project_managers').exists():
        role = "Project Manager"
    else:
        role = "Team Member"

    sorted_projects = Project.objects.filter(
        users_assigned=request.user.id).order_by('title')

    return render(request, 'accounts/profile_view.html',
                  {'user': user, 'role': role, 'project_list': sorted_projects})


#! Security Misconfiguration - Cross Site Request Forgery (CSRF)
@csrf_exempt
def profile_by_id(request, user_id):
    user = User.objects.get(pk=user_id)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            print("made it!")
            if request.POST.get('username') != user.username:
                user.username = request.POST.get('username')
            if request.POST.get('first_name') != user.first_name:
                user.first_name = request.POST.get('first_name')
            if request.POST.get('last_name') != user.last_name:
                user.last_name = request.POST.get('last_name')
            if request.POST.get('email') != user.email:
                user.email = request.POST.get('email')
            if request.POST.get('password'):
                user.set_password(request.POST.get('password'))
            if request.FILES:
                user.userprofile.image = store_uploaded_file(user.username
                                                             + "." + request.FILES['picture'].name.split(".")[-1], request.FILES['picture'])
                user.userprofile.save()
            user.save()
            messages.info(request, "User Updated")

    return render(request, 'accounts/profile.html', {'user': user})


def reset_password(request):

    if request.method == 'POST':

        reset_token = request.POST.get('reset_token')

        try:
            userprofile = UserProfile.objects.get(reset_token=reset_token)
            if timezone.now() > userprofile.reset_token_expiration:
                # Reset the token and move on
                userprofile.reset_token_expiration = timezone.now()
                userprofile.reset_token = ''
                userprofile.save()
                return redirect('/')

        except UserProfile.DoesNotExist:
            messages.warning(request, 'Invalid password reset token')
            return render(request, 'accounts/reset_password.html')

        new_password = request.POST.get('new_password')
        confirm_password = request.POST.get('confirm_password')
        if new_password != confirm_password:
            messages.warning(request, 'Passwords do not match')
            return render(request, 'accounts/reset_password.html')

        # Reset the user's password + remove the tokens
        userprofile.user.set_password(new_password)
        userprofile.reset_token = ''
        userprofile.reset_token_expiration = timezone.now()
        userprofile.user.save()
        userprofile.save()

        messages.success(request, 'Password has been successfully reset')
        return redirect('/login')

    return render(request, 'accounts/reset_password.html')


def forgot_password(request):

    if request.method == 'POST':
        t_email = request.POST.get('email')

        try:
            reset_user = User.objects.get(email=t_email)

            # Generate secure random 6 digit number
            res = ""
            nums = [x for x in os.urandom(6)]
            for x in nums:
                res = res + str(x)

            reset_token = res[:6]
            reset_user.userprofile.reset_token = reset_token
            reset_user.userprofile.reset_token_expiration = timezone.now() + \
                datetime.timedelta(minutes=10)
            reset_user.userprofile.save()
            reset_user.save()

            messages.success(
                request, 'Check your email(dosen\'t support) for a reset token. reset_token:' + reset_token)
            return redirect('/reset_password')
        except User.DoesNotExist:
            messages.warning(request, 'Check your email for a reset token')

    return render(request, 'accounts/forgot_password.html')


def change_password(request):

    if request.method == 'POST':
        user = request.user
        old_password = request.POST.get('old_password')
        new_password = request.POST.get('new_password')
        confirm_password = request.POST.get('confirm_password')

        if authenticate(username=user.username, password=old_password):
            if new_password == confirm_password:
                user.set_password(new_password)
                user.save()
                messages.success(request, 'Password Updated')
            else:
                messages.warning(request, 'Passwords do not match')
        else:
            messages.warning(request, 'Invalid Password')

    return render(request,
                  'accounts/change_password.html',
                  {'user': request.user})


#! Open Redirect
def logout_view(request):
    logout(request)
    return redirect(request.GET.get('redirect', '/'))

taskManager/views/dashboard.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse

from taskManager.models import Task, Project


def index(request):
    sorted_projects = Project.objects.order_by('-start_date')

    admin_level = False

    if request.user.groups.filter(name='admin_g').exists():
        admin_level = True

    list_to_show = []
    for project in sorted_projects:
        if (project.users_assigned.filter(username=request.user.username)).exists():
            list_to_show.append(project)

    if request.user.is_authenticated:
        return redirect("/dashboard")
    else:
        template = loader.get_template('index.html')
        context = {}
        return HttpResponse(template.render(context, request))


def dashboard(request):
    sorted_projects = Project.objects.filter(
        users_assigned=request.user.id).order_by('title')
    sorted_tasks = Task.objects.filter(
        users_assigned=request.user.id).order_by('title')
    return render(request,
                  'dashboard.html',
                  {'project_list': sorted_projects,
                   'user': request.user,
                   'task_list': sorted_tasks})


def search(request):
    query = request.GET.get('q', '')

    my_project_list = Project.objects.filter(
        users_assigned=request.user.id).filter(
            title__icontains=query).order_by('title')
    my_task_list = Task.objects.filter(
        users_assigned=request.user.id).filter(
            title__icontains=query).order_by('title')
    return render(request,
                  'search.html',
                  {'q': query,
                   'task_list': my_task_list,
                   'project_list': my_project_list,
                   'user': request.user})

taskManager/templates/tasks/manage_tasks.html
{% extends 'common/base_backend.html' %}
{% block content %}
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-6">
                <section class="panel">
                    <header class="panel-heading">
                        Assign user to task
                    </header>
                    <div class="panel-body">
                        <form method="post" role="form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>User</label>
                                <select name="userid" id="userid">
                                    {% for user in users %}
                                        <option value="{{user.id}}">{{user.get_full_name}} ({{user}})</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Task</label>
                                <select name="taskid" id="taskid">
                                    {% for task in tasks %}
                                        <option value="{{task.id}}">{{task.title}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-info">Update</button>
                            </div>
                        </form>

                    </div>
                </section>
            </div>

        </div>
    </section>

{% endblock %}

taskManager/templates/tasks/task_create.html
{% extends 'common/base_backend.html' %}

{% block content %}
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-6">
                <section class="panel">
                    <header class="panel-heading">
                        Create Task
                    </header>
                    <div class="panel-body">
                        <form method="post" role="form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Task Title</label>
                                <input name="task_title" class="form-control" placeholder="">
                                <label>Task Information</label>
                                <textarea name="text" class="form-control" placeholder=""></textarea>
                                <label>Task Due Date</label><br />
                                <input name="task_duedate" class="form-control" id="datetimepicker" type="text">
                            </div>
                            <button type="submit" class="btn btn-info">Finish</button>
                        </form>

                    </div>
                </section>
            </div>

        </div>
    </section>

{% endblock %}

taskManager/templates/tasks/task_details.html
{% extends 'common/base_backend.html' %}

{% block content   %}

    <!--main content start-->

    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel col-md-10">
            <header class="panel-heading">
                <!-- Cross Site Scripting (XSS) -->
                {{task.title|safe}}
                <span class="pull-right">
                    <a href="{% url 'task_edit' project_id=task.project.id task_id=task.id %}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit Task</a>
                    {% if task.completed %}
                        <a href="#" id="loading-btn" class="btn btn-success btn-xs" disabled="disabled"><i class="fa fa-check"></i> Task is Completed</a>
                    {% else %}
                        <a href="{% url 'task_complete' project_id=task.project.id task_id=task.id %}" class="btn btn-success btn-xs"><i class="fa fa-check"></i> Complete Task</a>
                    {% endif %}
                </span>
            </header>

        </section>
        <div class="row">
            <div class="col-md-10">
                <section class="panel">
                    <div class="panel-body">
                        <div class="row p-details">
                            <div class="col-md-5">
                                <p><span class="bold">Created:</span> {{task.start_date}} </p>
                            </div>
                            <div class="col-md-5">
                                <p><span class="bold">Due:</span> {{task.due_date}} </p>
                            </div>
                            <div class="col-md-5">
                                <p><span class="bold">Participants:</span>
                                    <span class="p-team">
                                        {% for u in task.users_assigned.all%}
                                            <a href="#"><img alt="image" src="{% url 'download_profile_pic' u.id %}"></a>
                                        {% endfor %}
                                    </span>
                                </p>
                            </div>
                            <div class="col-md-10">
                                <p><span class="bold">Description:</span>
                                    <span class="p-team">
                                        <!-- Cross Site Scripting (XSS) -->
                                        {{task.text|safe}}
                                    </span>
                                </p>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="panel">
                    <div class="panel-body">
                        <div class="row p-details">
                            <div class="col-md-10">
                                <span class="bold">Notes</span>
                                <span class="pull-right">
                                    <a href="{% url 'note_create' project_id=task.project.id task_id=task.id %}" class="btn btn-primary btn-xs"> Add Note</a>
                                </span>
                            </div>
                        </div>
                        <div class="row p-details">
                            <div class="col-md-10">
                                <span class="p-team">
                                    <table class="table table-hover p-table">
                                        <thead>
                                            <tr>
                                                <th>Title</th>
                                                <th>Text</th>
                                                <th>Edit</th>
                                                <th>Del</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for note in task.notes_set.all%}
                                                <tr>
                                                    <td>
                                                        {{note.title}}
                                                    </td>
                                                    <td>
                                                        {{note.text}}
                                                    </td>
                                                    <td><a href="{% url 'note_edit' project_id=task.project.id task_id=task.id note_id=note.id %}">Edit</a></td>
                                                    <td><a href="{% url 'note_delete' project_id=task.project.id task_id=task.id note_id=note.id %}">Delete</a></td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </span>
                            </p>
                        </div>
                    </div>

                </div>

            </section>

        </div>
    </div>
    <!-- page end-->
    </section>

{% endblock %}

taskManager/templates/tasks/task_edit.html
{% extends 'common/base_backend.html' %}

{% block content %}
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-6">
                <section class="panel">
                    <header class="panel-heading">
                        Edit Task
                        <span class="pull-right">
                            <a href="{% url 'note_create' project_id=task.project.id task_id=task.id %}" class="btn btn-primary btn-xs">Add Note</a>
                            {% if task.completed %}
                                <a href="#" id="loading-btn" class="btn btn-success btn-xs" disabled="disabled"><i class="fa fa-check"></i>Task is Completed</a>
                            {% endif %}
                        </span>
                    </header>
                    <div class="panel-body">
                        <form method="post" role="form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Enter Task Title</label>
                                <input name="task_title" class="form-control" value ="{{task.title}}">
                                <label>Enter Task Information</label>
                                <textarea name="text" class="form-control">{{task.text}}</textarea>
                                <label>Task Completion</label>
                                <input type="radio" name="task_completed" value="1" {% if task.completed %}checked{% endif %}> Yes&nbsp;
                                <input type="radio" name="task_completed" value="0" {% if not task.completed %}checked{% endif %}> No
                            </div>
                            <button type="submit" class="btn btn-info">Finish</button>
                        </form>

                    </div>
                </section>
            </div>

        </div>
    </section>

{% endblock %}

taskManager/templates/tasks/task_list.html
{% extends 'common/base_backend.html' %}
{% block content %}

    <!--main content start-->

    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            {% include 'common/messages.html'%}
            <header class="panel-heading">
                My Tasks
                <span class="pull-right">
                    <a href="{% url 'task_list' %}" id="loading-btn" class="btn btn-warning btn-xs"><i class="fa fa-refresh"></i>Refresh</a>
                </span>
            </header>

            <table class="table table-hover p-table">
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Project</th>
                        <th>Created</th>
                        <th>Due</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% if task_list %}
                        {% for task in task_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'task_details' project_id=task.project.id task_id=task.id %}">{{task.title}}</a>
                                </td>
                                <td>
                                    <a href="{% url 'project_details' task.project.id %}">{{task.project.title}}</a>
                                </td>
                                <td>
                                    {{task.start_date}}
                                </td>
                                <td>
                                    {{task.due_date}}
                                </td>
                                <td>
                                    <a href="{% url 'task_details' project_id=task.project.id task_id=task.id %}" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                    <a href="{% url 'task_edit' project_id=task.project.id task_id=task.id %}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                    <a href="{% url 'task_delete' project_id=task.project.id task_id=task.id %}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <div class="col-md-12">
                            <p>No tasks are assigned to you.</p>
                        </div>
                    {% endif %}
                </tbody>
            </table>
        </section>
        <!-- page end-->
    </section>

    <!--main content end-->
{% endblock %}